IF SCHEMA_ID(N'Chesscom') IS NULL
    EXEC (N'CREATE SCHEMA [Chesscom];');
GO

DROP TABLE IF EXISTS Chesscom.Player;
GO

CREATE TABLE Chesscom.Player(
    PlayerId INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
    Username NVARCHAR(128) NOT NULL UNIQUE,
    ChesscomId INT NOT NULL UNIQUE,
    Avatar NVARCHAR(128),
    Title NVARCHAR(8),
    [Status] NVARCHAR(32),
    [Name] NVARCHAR(128),
    IsRemoved BIT NOT NULL DEFAULT(0),
    CreatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET()),
    UpdatedOn DATETIMEOFFSET NOT NULL DEFAULT(SYSDATETIMEOFFSET())
);
GO